- name: install nginx
  ansible.builtin.apt:
    name: nginx
    state: latest

- name: Copy Nginx default config to sites-enabled
  template:
    src:  default.j2
    dest: /etc/nginx/sites-enabled/default
  notify: restart nginx

- name: start n enable nginx
  service:
    name: nginx
    state: started
    enabled: yes
    
### nginx exporter part

- name: Install nginx exporter
  apt:
    name: prometheus-nginx-exporter
  notify: 
    - Reload systemd
    - Restart Nginx exporter

- name: Enable exporter
  service:
    name: prometheus-nginx-exporter
    state: started
    enabled: yes
