- name: Install uwsgi packages
  apt:
    pkg:
    - uwsgi
    - uwsgi-plugin-python3
    - python3-pymysql

- name: start n enable uwsgi
  service:
    name: uwsgi
    state: started
    enabled: yes

- name: copy the uwsgi config file
  template:
    src:  agama.ini
    dest: /etc/uwsgi/apps-enabled/agama.ini
    owner: agama
    mode: 0600
  no_log: true
  notify: restart uwsgi


