{
 "title": "Main",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "dns selects/minute",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(bind_resolver_queries_total[1m])"
    }
   ]
  },
  {
   "title": "mysql selects/minute",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "rate(mysql_global_status_commands_total{command=\"select\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory consumption",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes{instance!=\"localhost:9100\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU load",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 17, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(node_cpu_seconds_total{mode=\"user\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "mysql status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_up{job=\"mysql_exporter\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": " http Requests/minute ",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(nginx_http_requests_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bind9 status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 12, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bind_up{job=\"bind_exporter\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nginx status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 17, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nginx_up", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 8 },
   "targets": [
    {
     "measurement": "latency",
     "select": [
      [
       { "params": [ "rtt" ], "type": "field" },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       }
      ]
     ],
     "tags": [
      { "key": "dst::tag", "operator": "=", "value": "cloudflare.com" }
     ]
    },
    {
     "measurement": "latency",
     "select": [
      [
       { "params": [ "rtt" ], "type": "field" },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       }
      ]
     ],
     "tags": [
      { "key": "dst::tag", "operator": "=", "value": "google.com" }
     ]
    },
    {
     "measurement": "latency",
     "select": [
      [
       { "params": [ "rtt" ], "type": "field" },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       }
      ]
     ],
     "tags": [
      { "key": "dst::tag", "operator": "=", "value": "twitter.com" }
     ]
    }
   ]
  },
  {
   "title": "InfluxDB write rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 8 },
   "targets": [
    {
     "expr": "influxdb_write_write_ok{instance=\"stealandsell-2:9424\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Haproxy status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "haproxy_up{job=\"haproxy\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Haproxy server status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 15, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "haproxy_server_up{job=\"haproxy\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "InfluxDB health",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "influxdb_exporter_stats_query_success{instance=\"stealandsell-2:9424\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Keepalived state",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 15, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "keepalived_vrrp_state{job=\"keepalived\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}