- name: Create agama dierectory
  file:
    path: /opt/agama
    state: directory

    
- name: download dockerfile and agama itself
  get_url:
    url: "{{ item.src }}"
    dest: "{{ item.dest }}"
  loop:
    - { src: "https://raw.githubusercontent.com/hudolejev/agama/master/Dockerfile", dest: "/opt/agama/Dockerfile"}
    - { src: "https://raw.githubusercontent.com/hudolejev/agama/master/agama.py", dest: "/opt/agama"}
    

- name: build agama
  community.docker.docker_image:
    name: agama
    source: build
    build:
      path: /opt/agama
      network: host
  
- name: run agama instances
  community.docker.docker_container:
    container_default_behavior: no_defaults
    name:  agama_{{ item }}
    image: agama
    published_ports: "{{ agama_start_port + item}}:{{agama_start_port-1}}"
    env:
       AGAMA_DATABASE_URI=mysql+pymysql://{{ mysql_user }}:{{ mysql_password }}@{{ mysql_host }}/{{ mysql_database }}
    restart_policy: always
  loop: "{{ range(agama_per_vm) }}"
  no_log: true
  
