###### mysql server part

- name: Install mysql server
  apt:
    name: mysql-server

- name: start mysql server
  service:
    name: mysql
    state: started
    enabled: yes

- name: override 
  copy:
    src:  override.cnf
    dest: /etc/mysql/mysql.conf.d/override.cnf
  notify: restart mysql

- name: Install Pymsql
  apt:
    pkg: 
    - python3-pymysql

- name: MySQL database
  community.mysql.mysql_db:
    name: "{{ mysql_database }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: Database user
  mysql_user:
    name: "{{ mysql_user }}"
    host: "%"
    password: "{{ mysql_password }}"
    priv: "{{ mysql_database }}.*:ALL"
    login_unix_socket: /var/run/mysqld/mysqld.sock
    
    
    
###### mysql exporter part

- name: Install dependecies
  apt:
    name: 
      - prometheus-mysqld-exporter
      - python3-pymysql

- name: Create directory
  file:
    path: /var/lib/prometheus
    state: directory

- name: Configure MySQL exporter
  template:
    src: .my.cnf
    dest: /var/lib/prometheus/.my.cnf
    owner: prometheus
    group: prometheus
    mode: 0600
  notify: Restart MySQL exporter

- name: Create MySQL exporter user
  mysql_user:
    name: "{{ mysql_ex_u }}"
    password: "{{ mysql_ex_p }}"
    priv: "*.*:PROCESS,REPLICATION CLIENT,SELECT"
    login_unix_socket: /var/run/mysqld/mysqld.sock
  no_log: true

- name: Force all notified handlers to run at this point, not waiting for normal sync points
  meta: flush_handlers

- name: Enabled
  service:
    name: prometheus-mysqld-exporter
    state: started
    enabled: yes
