###### mysql server part

- name: Install mysql server
  apt:
    name: mysql-server

- name: start mysql server
  service:
    name: mysql
    state: started
    enabled: yes

- name: override 
  template:
    src:  override.cnf
    dest: /etc/mysql/mysql.conf.d/override.cnf
  notify: restart mysql

- name: Install Pymsql
  apt:
    pkg: 
    - python3-pymysql

- name: MySQL database
  community.mysql.mysql_db:
    name: "{{ mysql_database }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
  notify:
    - source reset
    - reset replica
   
    
- name: Create MySQL users
  mysql_user:
    name: "{{ item.name }}"
    password: "{{ item.password }}"
    priv: "{{ item.priv }}"
    host: "%"
    login_unix_socket: /var/run/mysqld/mysqld.sock
  loop:
    - { name: "{{ mysql_user }}", password: "{{ mysql_password }}", priv: "{{ mysql_database }}.*:ALL" }
    - { name: "{{ mysql_ex_u }}", password: "{{ mysql_ex_p }}", priv: "*.*:PROCESS,REPLICATION CLIENT,SELECT" }
    - { name: "{{ mysql_replication_u }}", password: "{{ mysql_replication_p }}", priv: "*.*:REPLICATION SLAVE" }
  notify: restart mysql
  no_log: true
    
- name: replica  read-only ON
  community.mysql.mysql_variables:
    variable: read_only
    value: "{{ 'OFF' if inventory_hostname == mysql_host else 'ON' }}"
    mode: persist
    login_unix_socket: /var/run/mysqld/mysqld.sock
  notify:
    - source reset
    - reset replica
    
###### mysql exporter part

- name: Install dependecies
  apt:
    name: 
      - prometheus-mysqld-exporter
      - python3-pymysql

- name: Create directory
  file:
    path: /var/lib/prometheus
    state: directory



- name: copy confs
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: prometheus
    group: prometheus
    mode: 0600
  loop:
    - { src: ".exporter.my.cnf", dest: "/var/lib/prometheus/.my.cnf" }
    - { src: "etc.default", dest: "/etc/default/prometheus-mysqld-exporter" }
  notify: restart mysql exporter
  no_log: true


- name: Force all notified handlers to run at this point, not waiting for normal sync points
  meta: flush_handlers

- name: Enabled
  service:
    name: prometheus-mysqld-exporter
    state: started
    enabled: yes
    
    
### mysql backup 


- name: create backup/mysql directory     
  file:
    path: /home/backup/mysql
    state: directory
    mode: 0700
    owner: backup
    group: backup
    

- name: Move backup.my.cnf file
  template:
    src: .backup.my.cnf
    dest: /home/backup/.my.cnf
    owner: backup
    group: backup
    mode: 0400
  no_log: true
    
- name: Create user backup
  community.mysql.mysql_user:
    name: "{{ backup_u }}"
    password: "{{backup_p}}"
    priv:
      '*.*': 'LOCK TABLES,SELECT'
    login_unix_socket: /var/run/mysqld/mysqld.sock
  no_log: true
  
- name: create backup file
  template:
    src: mysql-backup
    dest: /etc/cron.d/mysql-backup
