- name: add keepalived_script user
  user:
    name: keepalived_script
    home: /home/keepalived_script
    shell: /bin/bash


- name: Install Keepalived
  apt: 
    name: keepalived

- name: Copy keepalived script file
  copy:
    src: vrrp_script.sh
    dest: /home/keepalived_script/vrrp_script
    owner: keepalived_script
    group: keepalived_script
    mode: 0770
  notify: 
    - restart daemon
    - restart keepalived



- name: copy confs
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  loop:
    - { src: "keepalived.conf.j2", dest: "/etc/keepalived/keepalived.conf" }
    - { src: "keepalived_exporter", dest: "/etc/systemd/system/keepalived_exporter.service" }
  notify: 
    - restart daemon
    - restart keepalived

- name: Extract exporter into folder
  unarchive:
    src: https://github.com/mehdy/keepalived-exporter/releases/download/v1.2.0/keepalived-exporter-1.2.0.linux-amd64.tar.gz
    dest: /usr/local/bin
    remote_src: yes
    
- name: execute handlers
  meta: flush_handlers

- name: Start keepalived on boot
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop:
    - keepalived
    - keepalived_exporter
