- name: restart mysql
  service:
    name: mysql
    state: restarted
    
- name: restart mysql exporter
  service:
    name: prometheus-mysqld-exporter
    state: restarted
    enabled: yes
    
- name: source reset 
  community.mysql.mysql_replication:
    mode: "{{ item }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
  loop:
    - stopreplica
    - resetprimary
  when: inventory_hostname == mysql_host 

- name: reset replica
  community.mysql.mysql_replication:
    mode: "{{ item }}"
    primary_host: "{{ mysql_host  }}"
    primary_user: "{{ mysql_replication_u }}"
    primary_password: "{{ mysql_replication_p }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
  loop:
    - stopreplica
    - changeprimary
    - resetreplica
    - startreplica
  when: inventory_hostname != mysql_host 
