- name: Install bind
  apt:
    name: 
      - bind9
      - python3-dnspython 
    state: latest

- name: copy the config 
  template:
    src:  named.conf.options
    dest: /etc/bind/named.conf.option
  notify: restart bind9

- name: DNS Zone
  template:
    src: db.gamblinggreats.io.j2
    dest: /var/lib/bind/db.gamblinggreats.io
  notify: reload rndc

- name: Stop systemd-resolved
  service:
    name: systemd-resolved
    state: stopped

- name: Change DNS configuration 
  template:
    src: resolv.conf.j2
    dest: /etc/resolv.conf
