- name: Install bind
  apt:
    name: 
      - bind9
      - python3-dnspython 
    state: latest

- name: copy the config 
  template:
    src:  named.conf.options
    dest: /etc/bind/named.conf.options
  notify: restart bind9

- name: DNS Zone
  template:
    src: db.gamblinggreats.io.j2
    dest: /var/lib/bind/db.gamblinggreats.io
  notify: reload rndc


### bind exporter part

- name: Install Bind9 exporter
  apt:
    name: prometheus-bind-exporter

- name: Enable Bind9 exporter
  service:
    name: prometheus-bind-exporter
    state: started
    enabled: yes
