#- name: Ansible ping module
#  ansible.builtin.ping:
  
#- name: juri
#  user:
#    name: juri

#- name: roman
#  user:
#    name: roman

#- name: SSH_roman
#  authorized_key:
#    user: roman
#    key: https://github.com/romankuchin.keys

#- name: SSH_juri
#  authorized_key:
#    user: juri
#    key: https://github.com/hudolejev.keys
    
- name: Update APT cache
  ansible.builtin.apt:
    cache_valid_time: 86400
