#- name: Ansible ping module
#  ansible.builtin.ping:
  
#- name: juri
#  user:
#    name: juri

#- name: roman
#  user:
#    name: roman

#- name: SSH_roman
#  authorized_key:
#    user: roman
#    key: https://github.com/romankuchin.keys

#- name: SSH_juri
#  authorized_key:
#    user: juri
#    key: https://github.com/hudolejev.keys
    
- name: Update APT cache
  ansible.builtin.apt:
    cache_valid_time: 86400

### prometheus exporter part

- name: install packages
  apt:
    name: 
      - prometheus-node-exporter

- name: start & enable node exporter
  service:
    name: prometheus-node-exporter
    state: started
    enabled: yes
    
### ca certificates part
    
- name: Ensure ca-certificates is up-to-date
  apt:
    name: ca-certificates=20230311ubuntu0.20.04.1
    
#### syslog part

- name: install rsyslog
  apt:
    name: rsyslog
    state: latest

- name: copy conf
  template:
    src: 50-telegraf.conf
    dest: /etc/rsyslog.d/50-telegraf.conf
  notify: restart rsyslog
  
- name: Start & enable
  service:
    name: rsyslog
    state: started
    enabled: yes
    
    
### backup part

- name: install duplicity
  apt:
    name: duplicity

- name: create backup user
  user:
    name: backup
    home: /home/backup
    generate_ssh_key: yes
    shell: /bin/bash

    
- name: create restore directory     
  file:
    path: /home/backup/restore
    state: directory
    mode: 0700
    owner: backup
    group: backup
    
- name: Create template known_hosts
  template: 
    src: known_hosts
    dest: /home/backup/.ssh/known_hosts
    mode: 0644
    owner: backup
    group: backup

- name: copy conf
  template:
    src: 50-telegraf.conf
    dest: /etc/rsyslog.d/50-telegraf.conf
  notify: restart rsyslog
  
- name: Start & enable
  service:
    name: rsyslog
    state: started
    enabled: yes

